#!/bin/bash

# Don't run me as root!
if [[ `id --user` == "0" ]]; then
    echo "Do not run jenkins as root."
    exit 1
fi

# Use virtualenv with Django-1.5 installed.
source /home/tbp/virtualenv/django15/bin/activate

# The following conditions must be true for jenkins to return true:
#   1. The tests must pass.
#   2. pylint must be perfect, as evidenced by a perfect score of "10.00/10".
#   3. pep8 must be perfect, as evidenced by no lines with "py" in the report.
# All other lint errors are not taken into consideration for the +/- Verified
# flag. Jenkins will report the other lint errors in pretty graphs though.
python manage.py jenkins \
    --settings=quark.settings.test \
    --pep8-max-line-length=80
jenkins_status=$?
grep -q "Your code has been rated at 10.00/10" reports/pylint.report
pylint_status=$?
grep -q "py" reports/pep8.report
pep8_status=$?

if [[ ($jenkins_status == 0) && ($pylint_status == 0) && ($pep8_status != 0) ]]; then
    echo -e "\nEverything looks good!"
    exit 0
else
    if [[ $pylint_status != 0 ]]; then
        echo -e "\nPYLINT VIOLATIONS"
        echo "================================================================"
        grep "^quark" reports/pylint.report
    else
        echo -e "\nNo pylint violations."
    fi

    if [[ $pep8_status == 0 ]]; then
        echo -e "\nPEP8 VIOLATIONS"
        echo "================================================================"
        cat reports/pep8.report
    else
        echo -e "\nNo pep8 violations."
    fi

    echo -e "\nPlease fix all errors before doing git review!"
    exit 1
fi
